### ISSUE TITLE
Zoro get anime streaming links with subtitles not working

### ISSUE THREAD

**Issue by ShShr08** [consumet/consumet-api#119]
### Describe the bug

zoro provider is working, however the /watch?episodeId path isnt working

### Steps to reproduce

go to https://consumet-api.herokuapp.com/anime/zoro/watch?episodeId=spy-x-family-17977$episode$89506 (or any other anime)
Doesnt return data.
The error message is empty so you cant make out why its not working (404, 400, 500)

### Expected behavior

{data: {...}}

### Actual behavior

{"message":{}}

**Comment by riimuru** [comment]
fixed 👍

**Comment by Awe03** [comment]
@riimuru i've found that certain series itself dont return streaming links with empty messages, same issue as @ShShr08 was facing
Ex: naruto shippuden, half of spy x family, etc

**Comment by riimuru** [comment]
@Awe03 its working now

**Comment by Awe03** [comment]
Oh alright
