### ISSUE TITLE
Zoro watch api returns 404 albeit correct episodeId

### ISSUE THREAD

**Issue by tdattran1707** [consumet/consumet-api#123]
### Describe the bug

zoro watch api returns {"message":{}} although I pass in the correct episode Id

### Steps to reproduce

I get this "bleach-the-movie-fade-to-black-1492$episode$58326" id from zoro info api and pass in the link "https://consumet-api.herokuapp.com/anime/zoro/watch?episodeId=bleach-the-movie-fade-to-black-1492$episode$58326" 

it returns  404

### Expected behavior

this is the link:
https://consumet-api.herokuapp.com/anime/zoro/watch?episodeId=bleach-the-movie-fade-to-black-1492$episode$58326

it should return data

### Actual behavior

https://consumet-api.herokuapp.com/anime/zoro/watch?episodeId=bleach-the-movie-fade-to-black-1492$episode$58326
returns  {"message":{}} instead of data

**Comment by riimuru** [comment]
@tdattran1707 the link is working for me

**Comment by riimuru** [comment]
@tdattran1707 i just fixed it
