### ISSUE TITLE
axios rate limit

### ISSUE THREAD

**Issue by Awe03** [consumet/consumet-api#124]
### Describe the bug

The axios rate limit prevents app to fetch data from zoro

### Steps to reproduce

https://consumet-api.herokuapp.com/anime/zoro/watch?episodeId=demon-slayer-entertainment-district-arc-17483$episode$84969

### Expected behavior

{data: [...]}

### Actual behavior

{"message":{"message":"Request failed with status code 429","name":"AxiosError","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.27.2"},"method":"get","url":"https://rapidclown.riimuru.workers.dev/rapidclown"},"code":"ERR_BAD_REQUEST","status":429}}

### Additional context

This only happens for zoro, not other providers

checking https://rapidclown.riimuru.workers.dev/rapidclown shows

![image](https://user-images.githubusercontent.com/106132059/190322218-7ecc22af-9b7e-41bd-acf6-e39b11c67418.png)

**Comment by riimuru** [comment]
@Awe03 That is my cf worker, and I am aware of the error. I was ddosed, thats why it got rate limited.

**Comment by Awe03** [comment]
ah alright

**Comment by riimuru** [comment]
@Awe03 fixed. it should be up in a sec
