### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by vanelk** [consumet/consumet-api#56]
Hey I was working with the API and suddenly it stopped working. I think you might have an application error on your Heroku server

**Comment by riimuru** [comment]
@vanelk sorry about that, somone was abusing it. It should be working now.

**Comment by SlideMovies** [comment]
> 

Abusing!??! 🤯

**Comment by riimuru** [comment]
@vanelk @SlideMovies this is the guy who was abusing it, give him a word please :).
