### ISSUE TITLE
Feature Request: Get seek thumbnails (Zoro.to)

### ISSUE THREAD

**Issue by SlideMovies** [consumet/consumet-api#57]
<img width="362" alt="Screenshot 2022-08-04 at 5 22 35 PM" src="https://user-images.githubusercontent.com/87663026/182845860-5946e477-6ad4-42c6-9051-a1355dccc93a.png">
Get seek thumbnails from zoro.to

**Comment by vanelk** [comment]
That is a seek feature

**Comment by SlideMovies** [comment]
@vanelk Didn't know the name, thanks for telling.

**Comment by vanelk** [comment]
@SlideMovies No problem

**Comment by vanelk** [comment]
@SlideMovies I'm currently creating an electron app using this API. Do you know any media player component I can use to stream episodes I got from the API links?

**Comment by SlideMovies** [comment]
@vanelk just use HLS.js

**Comment by vanelk** [comment]
@SlideMovies Thanks gonna give it a try. I'm gonna keep you guys posted.

**Comment by riimuru** [comment]
@vanelk many people on the discord server are building apps. You sure yoy will benefit a lot from them if you want to join. https://github.com/consumet/consumet-api#support

**Comment by vanelk** [comment]
@riimuru Thanks

**Comment by riimuru** [comment]
@vanelk @SlideMovies this feature already exists, and you can find the seek thumbails file in the subtitles array, and marked as `Default (maybe)` in the `lang` property.
```
{"url":"...", "lang": Default (maybe)"}
```
